name: Verify

on:
  pull_request:
    branches:
      - latest

jobs:
  verify_code:
    name: Compile
    runs-on: ubuntu-22.04
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          architecture: x64
          cache: maven
      - name: Setup environment
        run: |
          sudo apt-get install unzip
          wget -O starsector.zip "https://f005.backblazeb2.com/file/fractalsoftworks/release/starsector_linux-0.98a-RC8.zip"
          unzip starsector.zip -d starsector-root
          wget -O lazylib.zip "https://github.com/LazyWizard/lazylib/releases/download/3.0/LazyLib.3.0.zip"
          unzip lazylib.zip -d starsector-root/starsector/mods
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "starsector-root/starsector/mods/vppps"
      - name: CD
        run: |
          cd ${GITHUB_WORKSPACE}/starsector-root/starsector
          echo "Starsector directory"
          ls -l .
          echo "Mods directory"
          cd mods
          ls -l .
          echo "Our directory"
          cd vppps
          ls -l .
      - name: Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: JAR
          path: jars